### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by wangshun1121** [ShenLab-Genomics/MAGPIE#1]
请问可否提供运行整套程序的docker image? 或者是Dockerfile，我们自己构建image？

**Comment by wangshun1121** [comment]
另外，发现环境配置文件中设计cuda，那么整套工具可否有纯CPU方案？

**Comment by yczju** [comment]
> 请问可否提供运行整套程序的docker image? 或者是Dockerfile，我们自己构建image？

您好！欢迎您使用工具并提出宝贵意见。我将尽快将DockerFile发布，在此之前，您仍然可以通过readme中的步骤配置环境并运行程序。

**Comment by yczju** [comment]
> 另外，发现环境配置文件中设计cuda，那么整套工具可否有纯CPU方案？

cuda主要用于运行SpliceAI以注释突变，若仅使用CPU可忽略这部分配置，但请注意注释大量突变会较耗时。以Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz CPU为例，SpliceAI运行速度约为1.68it/s.

**Comment by wangshun1121** [comment]
> > 另外，发现环境配置文件中设计cuda，那么整套工具可否有纯CPU方案？
> 
> cuda主要用于运行SpliceAI以注释突变，若仅使用CPU可忽略这部分配置，但请注意注释大量突变会较耗时。以Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz CPU为例，SpliceAI运行速度约为1.68it/s.

明白了。若不重新训练新模型，仅仅采用已有模型预测，将Splicing Sites挑出来，一个样品大概几百个，运行时间预计5-10min，也可以接受。

**Comment by yczju** [comment]
> 请问可否提供运行整套程序的docker image? 或者是Dockerfile，我们自己构建image？

您好！抱歉久等，Dockerfile已发布，另外我们提供了magpie.yml配置文件方便大家快速简便地配置运行环境。
