### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by wonderful1** [ShenLab-Genomics/MAGPIE#2]
Hello, I am very interested in the MAGPIE. I attempted to install it using conda but encountered some difficulties. Would it be possible for you to provide a public docker image of the MAGPIE?

**Comment by yczju** [comment]
Thank you for using MAGPIE! I have already provided [Dockerfile](https://github.com/ShenLab-Genomics/MAGPIE/blob/main/Dockerfile) in the repo.
