### ISSUE TITLE
Cannot Sign Up in the web server

### ISSUE THREAD

**Issue by Cheerful0** [ShenLab-Genomics/MAGPIE#3]
I used the school email address but couldn't register successfully, the suffix of the mailbox is edu.cn

**Comment by yczju** [comment]
Sorry for the inconvenience during registering our web server. Could you please tell me more detailed info about the error?  For example in which step the error occurs and what the error message is?

**Comment by Cheerful0** [comment]
After I fill in all the information and click Register, It shows "Error: Only educational emails are allowed for registration!"

**Comment by yczju** [comment]
Thank you for reporting the bug to us! We have fixed this problem. Please try to register again.
